
export const redeemsAndExchangesTable = [
    { img: '', barCodeImg: '', address: 'PO Box 944881, Meadows 8-Street 2 Villa 15', fee: '274', expiryDate: 'December 25, 2025', city: 'Dubai', county: 'UAE', shippingOption: 'Standard Shipping', packageType: 'Gift Envelop', orderId: '#OrderID-999999', id: '01', date: 'August 17, 2024', time: '7:00 AM', customer: { name: 'Jordan Stevenson', email: 'dayna19@yahoo.com' }, product: { serviceName: 'Staycation', serviceDescription: 'Private Helicopter Tour Dubai' }, status: "Received", },
    { img: '', barCodeImg: '', address: 'PO Box 944881, Meadows 8-Street 2 Villa 15', fee: '274', expiryDate: 'December 25, 2025', city: 'Dubai', county: 'UAE', shippingOption: 'Standard Shipping', packageType: 'Gift Envelop', orderId: '#OrderID-999999', id: '02', date: 'August 17, 2024', time: '7:00 AM', customer: { name: 'Jordan Stevenson', email: 'dayna19@yahoo.com' }, product: { serviceName: 'Collection', serviceDescription: 'Private Helicopter Tour Dubai' }, status: "Processing", },
    { img: '', barCodeImg: '', address: 'PO Box 944881, Meadows 8-Street 2 Villa 15', fee: '274', expiryDate: 'December 25, 2025', city: 'Dubai', county: 'UAE', shippingOption: 'Standard Shipping', packageType: 'Gift Envelop', orderId: '#OrderID-999999', id: '03', date: 'August 17, 2024', time: '7:00 AM', customer: { name: 'Jordan Stevenson', email: 'dayna19@yahoo.com' }, product: { serviceName: 'Collection', serviceDescription: 'Private Helicopter Tour Dubai' }, status: "Processing", },
    { img: '', barCodeImg: '', address: 'PO Box 944881, Meadows 8-Street 2 Villa 15', fee: '274', expiryDate: 'December 25, 2025', city: 'Dubai', county: 'UAE', shippingOption: 'Standard Shipping', packageType: 'Gift Envelop', orderId: '#OrderID-999999', id: '04', date: 'August 17, 2024', time: '7:00 AM', customer: { name: 'Jordan Stevenson', email: 'dayna19@yahoo.com' }, product: { serviceName: 'Default', serviceDescription: 'Private Helicopter Tour Dubai' }, status: "Cancelled", },
    { img: '', barCodeImg: '', address: 'PO Box 944881, Meadows 8-Street 2 Villa 15', fee: '274', expiryDate: 'December 25, 2025', city: 'Dubai', county: 'UAE', shippingOption: 'Standard Shipping', packageType: 'Gift Envelop', orderId: '#OrderID-999999', id: '05', date: 'August 17, 2024', time: '7:00 AM', customer: { name: 'Jordan Stevenson', email: 'dayna19@yahoo.com' }, product: { serviceName: 'Staycation', serviceDescription: 'Private Helicopter Tour Dubai' }, status: "Cancelled", },
    { img: '', barCodeImg: '', address: 'PO Box 944881, Meadows 8-Street 2 Villa 15', fee: '274', expiryDate: 'December 25, 2025', city: 'Dubai', county: 'UAE', shippingOption: 'Standard Shipping', packageType: 'Gift Envelop', orderId: '#OrderID-999999', id: '06', date: 'August 17, 2024', time: '7:00 AM', customer: { name: 'Jordan Stevenson', email: 'dayna19@yahoo.com' }, product: { serviceName: 'Default', serviceDescription: 'Private Helicopter Tour Dubai' }, status: "Received", },
    { img: '', barCodeImg: '', address: 'PO Box 944881, Meadows 8-Street 2 Villa 15', fee: '274', expiryDate: 'December 25, 2025', city: 'Dubai', county: 'UAE', shippingOption: 'Standard Shipping', packageType: 'Gift Envelop', orderId: '#OrderID-999999', id: '07', date: 'August 17, 2024', time: '7:00 AM', customer: { name: 'Jordan Stevenson', email: 'dayna19@yahoo.com' }, product: { serviceName: 'Staycation', serviceDescription: 'Private Helicopter Tour Dubai' }, status: "Booking", },
]
